[env:esp32wrover]
platform = espressif32@6.7.0
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
    -DCORE_DEBUG_LEVEL=2
    -DBOARD_HAS_PSRAM
board_build.partitions = huge_app.csv   ; ~3MB app, ~1MB SPIFFS
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.psram = enabled
lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools.git#v1.1.3
    https://github.com/pschatzmann/arduino-libhelix.git